variables:
  ANALYTICS_IMAGE: $CI_REGISTRY_IMAGE/analytics:latest
  GATEWAY_IMAGE: $CI_REGISTRY_IMAGE/gateway:latest
  GENERATION_IMAGE: $CI_REGISTRY_IMAGE/generation:latest
  IDENTITY_IMAGE: $CI_REGISTRY_IMAGE/identity:latest
  PROJECT_IMAGE: $CI_REGISTRY_IMAGE/project:latest
  SCHEDULE_IMAGE: $CI_REGISTRY_IMAGE/schedule:latest
  FRONTEND_IMAGE: $CI_REGISTRY_IMAGE/frontend:latest

include:
  - local: 'ci/.templates.yml'

stages:
  - make_docker_images
  - deploy
  - logs

make_analytics_docker_image:
  extends: .make_docker_image
  variables:
    IMAGE: $ANALYTICS_IMAGE
    DOCKERFILE: ./Api/PositionAnalysisApi/Dockerfile

make_gateway_docker_image:
  extends: .make_docker_image
  variables:
    IMAGE: $GATEWAY_IMAGE
    DOCKERFILE: ./Api/APIGateway/Dockerfile    

make_generation_docker_image:
  extends: .make_docker_image
  variables:
    IMAGE: $GENERATION_IMAGE
    DOCKERFILE: ./Api/GenerationApi/Dockerfile
  
make_identity_docker_image:
  extends: .make_docker_image
  variables:
    IMAGE: $IDENTITY_IMAGE
    DOCKERFILE: ./Api/IdentityServerApi/Dockerfile

make_project_docker_image:
  extends: .make_docker_image
  variables:
    IMAGE: $PROJECT_IMAGE
    DOCKERFILE: ./Api/ProjectApi/Dockerfile

make_schedule_docker_image:
  extends: .make_docker_image
  variables:
    IMAGE: $SCHEDULE_IMAGE
    DOCKERFILE: ./Api/ScheduledSiteAnalyticsApi/Dockerfile

make_frontend_docker_image:
  extends: .make_docker_image
  variables:
    IMAGE: $FRONTEND_IMAGE
    DOCKERFILE: ./xetiumapi.client/Dockerfile

deploy_analytics:
  extends: .deploy
  variables:
    MANIFEST: ./ci/analytics.yaml

deploy_gateway:
  extends: .deploy
  variables:
    MANIFEST: ./ci/gateway.yaml    

deploy_generation:
  extends: .deploy
  variables:
    MANIFEST: ./ci/generation.yaml
  
deploy_identity:
  extends: .deploy
  variables:
    MANIFEST: ./ci/identity.yaml

deploy_project:
  extends: .deploy
  variables:
    MANIFEST: ./ci/project.yaml

deploy_schedule:
  extends: .deploy
  variables:
    MANIFEST: ./ci/schedule.yaml

deploy_frontend:
  extends: .deploy
  variables:
    MANIFEST: ./ci/frontend.yaml

logs_analytics:
  extends: .logs
  variables:
    DEPLOYMENT: analytics

logs_gateway:
  extends: .logs
  variables:
    DEPLOYMENT: gateway

logs_generation:
  extends: .logs
  variables:
    DEPLOYMENT: generation

logs_identity:
  extends: .logs
  variables:
    DEPLOYMENT: identity

logs_project:
  extends: .logs
  variables:
    DEPLOYMENT: project
  
logs_schedule:
  extends: .logs
  variables:
    DEPLOYMENT: schedule

logs_frontend:
  extends: .logs
  variables:
    DEPLOYMENT: frontend
